### ISSUE TITLE
Get flexible content sub field of type "gallery" via REST

### ISSUE THREAD

**Issue by pixeline** [airesvsg/acf-to-rest-api#100]
Hello, 

In this setup, custom post type "Page" has a Flexible Content field `content`, with, among other layouts, a layer `galleries` which contains a repeater (named `galleries`), which in turns contains a field of type `gallery` named `gallery_images`.

In other words: 

```
content (type: Flexible Content)
    L galleries (layout)
               L galleries (type: repeater)
                          L gallery_images (type: gallery)
```
From the frontend, I would like to fetch all the images of a given gallery via Ajax, using the Rest API, but It's not clear how can I address a specific gallery?

This url gets me all the data inside `content`: 
_http://localhost/wp-json/acf/v2/page/2/content_

But content being a FC, I then need to loop through the sub rows. It could possibly hold several layout "galleries" so I cannot filter using the layout. 

Any idea how I can do that?

Thank you for your help, 

Alexandre.

**Comment by airesvsg** [comment]
Hi @pixeline,
please look it: https://github.com/airesvsg/acf-to-rest-api/issues/9#issuecomment-175110946
Thanks

**Comment by akhanukov** [comment]
Hi @airesvsg, I've looked through all of the issues and see that you send everyone to Issue #9 and the resolution there. I've tried all instances and different combinations and I still can't get it to work, it being a relationship field, within a repeater, on a custom endpoint. Perhaps the issue in my case is that my endpoint isn't just a custom post type, but actually a combination of a custom class controller that replaces/extends WP_REST_Posts_Controller with some logic that queries one custom post type for data in an ACF field and then filters another custom post type based on if that field or data exists. Finally, it is called but a custom query variable. So my url is:

/wp-json/wp/v2/messages_in_interaction/?interactionID=6800 and the output is:

<img width="812" alt="acftorestapi-issue9-customcontroller" src="https://cloud.githubusercontent.com/assets/1213369/22360426/908938b4-e41d-11e6-8b6b-e85cc389b6b3.png">

As you'll see, I circled where I would like ACF fields to display. Note, that because I'm using the custom classes, /messages nor /interactions endpoints on their own don't work, yet display as linked data in the API. Any ideas? Thanks!

**Comment by akhanukov** [comment]
Hi @airesvsg, would it be better to create a new ticket for this?

**Comment by akhanukov** [comment]
Hi @airesvsg, I've gone ahead and created a new issue. Thank you!

**Comment by airesvsg** [comment]
https://github.com/airesvsg/acf-to-rest-api/issues/101#issuecomment-277564455

**Comment by airesvsg** [comment]
Hi @pixeline,
Can I close this issue?
Thanks
