### ISSUE TITLE
Cant update item

### ISSUE THREAD

**Issue by ticoti** [airesvsg/acf-to-rest-api#120]
Im trying to update custom field but get error cannot update item

I am autheticated with basic auth.

![image](https://cloud.githubusercontent.com/assets/8001543/24328663/69595f9e-11ef-11e7-8f65-b70a42f7fb0b.png)

**Comment by airesvsg** [comment]
Hi @ticoti,
This is an authentication error. 
Please, see more details about authentication in the link below.
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

Thanks

**Comment by ticoti** [comment]
But I am using basic auth and I can create,delete posts etc with normal  rest wp api

Is basic auth not working with acf-to-rest-api ?

If it set incorrect access data, the api call returns:

{
  "code": "rest_forbidden",
  "message": "Lo siento, no puedes hacer eso",
  "data": {
    "status": 403
  }
}

otherwise with correct auth data, it returns cannot update item

**Comment by airesvsg** [comment]
Hi @ticoti,
My plugin use the same strategy of WordPress Rest API.

Are you using the plugin below?
https://github.com/WP-API/Basic-Auth

If you are using, please update the file **basic-auth.php** to:
https://gist.githubusercontent.com/airesvsg/e8eeb54cf724284cbe5cf80a2b0451a1/raw/691628ff9effa009118a2f74ebf39a4ace97a26e/basic-auth.php

Thanks

**Comment by ticoti** [comment]
I changed to your plugin v2 version and It got to work

**Comment by airesvsg** [comment]
Hi @ticoti,
please change **Text** to **JSON (application/json)**
![change](https://user-images.githubusercontent.com/396668/28323534-8a1f0b2e-6baf-11e7-877e-80026b3491a9.png)
Thanks

**Comment by imokweb** [comment]
Hi,

I'm getting the same error. I've also updated the basic-auth.php but the error still persists.
Tried with V2 & V3. Same error
I've also tried with put & patch.

![image_119](https://user-images.githubusercontent.com/3976255/32900167-80680072-caf5-11e7-9f37-9ec9cc78bc26.png)

![image](https://user-images.githubusercontent.com/3976255/32900196-9518f850-caf5-11e7-86da-0d4f83ea5c37.png)

Can you please advise?
Thanks,
Istvan

**Comment by airesvsg** [comment]
Hi @imokweb,
Please, check your credentials.
I removed your first screenshot, see below the reason 😅 
```
user: ******ness
pass: elect******
```
Thanks

**Comment by imokweb** [comment]
Hello,
Thanks for removing the screenshot. 
The credentials are working, because I am able to create and update any Custom Post type & regular wp posts through the API. I've tried with Postman & also php curl.
Is there any way to insert acf data when creating a new post through the api?
Thanks,Istvan
 
 
 
Hi @imokweb,
Please, check your credentials.
I removed your first screenshot, see below the reason 😅
 user: ******ness
pass: elect******

Thanks

**Comment by imokweb** [comment]
Hello,

Thanks for removing the screenshot. 

The credentials are working, because I am able to create and update any Custom Post type & regular wp posts through the API. I've tried with Postman & also php curl.

Is there any way to insert acf data when creating a new custom post through the api?
Ca you please post an example json that adds acf data also to the new post?

Thanks,
Istvan

**Comment by airesvsg** [comment]
Hi @imokweb,
Please, see the To do list example
https://github.com/airesvsg/acf-to-rest-api#examples
Thanks

**Comment by CarlosDevlp** [comment]
Have the same error. It just doesn't work :(

**Comment by ianemv** [comment]
Mine seems to work on post and custom post type resources except for user resource.

{
    "code": "cant_update_item",
    "message": "Cannot update item",
    "data": {
        "status": 500
    }
}

**Comment by darick0029** [comment]
hi @ianemv  just wanna ask if you solved the problem on your end? I also have the same problem it works on post and post types but cannot make it work on the users acf fields.

**Comment by Crownie** [comment]
@darick0029 or anyone else from the future experiencing similar problem take a look at my comment here https://github.com/airesvsg/acf-to-rest-api-example/issues/1#issuecomment-874775399
