### ISSUE TITLE
JSON Format

### ISSUE THREAD

**Issue by jalane81** [airesvsg/acf-to-rest-api#216]
@airesvsg We have a few ACF fields in our Wordpress site and are trying to use the REST API to create a new page and post data into these fields.  We are creating a page for each Coach Profile and each field has things like BIO, AVATAR, Name, and a Link to Download our App and request services for that specific coach.

We are unable to figure out the proper JSON syntax and everything we've tried doesn't seem to work. 

From my engineer, 

here is what i thought was the correct json format:{“title”:“Title of API Page 2",“content”:“This is the page content.  This would be the bio.  It contains plain text.“, “meta”:{  
        “coachavatar”:“5”,
        “download”:“http:\/\/google.com\/#dynamiclink”,
        “coach_name”:“Planet Fitness”,
        “bio”:“My name is Coach. I offer services, XYZ..  Nice to meet you.  Click on the link below to download Heycoach and request my services.“}}

Can you help point us in the right direction here?  We have 4.9.4 and ACF 3.1.0 installed along with the latest version of the ACF to WP REST API plugin.  

Thank you!

Jason

**Comment by jalane81** [comment]
BTW: This is a test page we created and these fields actually have data in them, but they are showing "FALSE" 
http://159.203.106.83/wp-json/acf/v3/pages/43

**Comment by airesvsg** [comment]
Hi @jalane81,

you can find all endpoints allowed in the readme of my repository.

https://github.com/airesvsg/acf-to-rest-api#endpoints

You need to wrap all "ACF fields" with the "fields" key, look:

https://github.com/airesvsg/acf-to-rest-api#editing-the-fields

The JSON structure:

```JSON
{
  "fields": {
    "first_name": "Aires",
    "last_name": "Gonçalves"
  }
}
```

Please, read about authentication, because you must have to authenticate to edit all fields.

https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

Thanks
