### ISSUE TITLE
Relation add acf fields?

### ISSUE THREAD

**Issue by cannap** [airesvsg/acf-to-rest-api#223]
hi as example 
i have a

relation to a custom post type

now i need some acf fields in the relations output i got via acf but i dont know how :/

i use //xxxx.com/**wp-json/wp/v2/pages?slug=arbeiten**
![unbenannt](https://user-images.githubusercontent.com/1394151/37904401-f6f56ccc-30fb-11e8-9839-e377e50e3b2f.JPG)

**Comment by dmnsgn** [comment]
Hi @airesvsg and @rainboxx ,

I see you have been discussing the topic of adding acf fields to Relationship objects in the following PR https://github.com/airesvsg/acf-to-rest-api/pull/95 some time ago.

Is it implemented somehow or is there any workaround specifically with the ACF Pro v5?

Thanks

**Comment by rainboxx** [comment]
I'm no longer on the specific project where we used this plugin so can't really help here to tell how we implemented our case. I remember that we have changed how we use the API back then so we no longer had this requirement.

My PR was not implemented since I couldn't get it running with the Pro v5. I tried following-up but since priority and consumption changed I couldn't finish this.

**Comment by airesvsg** [comment]
Hi @dmnsgn,

I didn't the implementation, but you can use that solution: https://github.com/airesvsg/acf-to-rest-api/issues/109#issuecomment-286403063

Thanks

**Comment by dmnsgn** [comment]
Thanks for the pointers. Since I am using the `Custom Post Type UI` plugin, I ended up getting all the different post types (including customs) and add_filter for each:

```php
<?php
$post_types = array_merge(get_post_types(), cptui_get_post_type_slugs());

foreach ($post_types as $type) {
	add_filter(
		'acf/rest_api/' . $type . '/get_fields',
		function ($data, $response) use ($post_types) {
			if ($response instanceof WP_REST_Response) {
				$data = $response->get_data();
			}

			array_walk_recursive($data, 'get_fields_recursive', $post_types);

			return $data;
		},
		10,
		3
	);
}

function get_fields_recursive($item)
{
	if (is_object($item)) {
		$item->acf = array();

		if ($fields = get_fields($item)) {
			$item->acf = $fields;
			array_walk_recursive($item->acf, 'get_fields_recursive');
		}
	}
}
```

@cannap that should work fo you.

**Comment by airesvsg** [comment]
Hi @dmnsgn,

Please, test it:
https://github.com/airesvsg/acf-to-rest-api-recursive

Thanks

**Comment by cannap** [comment]
thanks all it works! now i can save some duplicated content and time  :D

**Comment by dmnsgn** [comment]
@airesvsg I can't manage to make it work with the recursive plugin but it might be because my Custom Post Type are handled via the CPTUI plugin and you need to use this function to retrieve them: [cptui_get_post_type_slugs()](http://codex.pluginize.com/cptui/v1.5.0/function-cptui_get_post_type_slugs.html)

**Comment by airesvsg** [comment]
Hi @dmnsgn,

Please, try it:
```PHP
add_filter( 'acf/rest_api/recursive/types', function( $types ) {
  $slugs = (array) cptui_get_post_type_slugs();

  $types += array_combine( $slugs, $slugs );

  return $types;
} );
```

Thanks

**Comment by dmnsgn** [comment]
Yep, that works fine!

**Comment by jaredpalmer** [comment]
Worked for me too!

**Comment by oggzr** [comment]
How do you prevent this from turning into a infinity loop? For example if one of the relation posts are the same as the parent post.
