### ISSUE TITLE
Tag taxonomy returns empty array!

### ISSUE THREAD

**Issue by gapgag55** [airesvsg/acf-to-rest-api#245]
`wp-json/acf/v3/tags`
`return []`

Problem is, it does not fetch the data from the server.
but Category taxonomy works.

Please help,
Thanks

**Comment by airesvsg** [comment]
Hi @gapgag55,

Not like it: https://github.com/airesvsg/acf-to-rest-api/issues/243#issuecomment-388365141

Thanks

**Comment by julesrenaud** [comment]
Hi, I found the issue.

My problem was't exactly the same but I'm sure the underlying issue is the same. I was trying to access acf data via the `wp/v2/tags` endpoint. The `acf` rest field was missing when using this endpoint but it was there when using the `wp/v2/categories` endpoint. The issue is that the tag taxonomy is named *post_tag* but is referred to as *tag* when using the `register_rest_field` function. When you register the field using `$this->type`, it needs to be parsed as *tag* if the type is *post_tag*.

Here's the hotfix I applied to *v3/lib/endpoints/class-acf-to-rest-api-controller.php*, line 51 (`register_field` function). I'm sure there's a similar mixup in the `register_hooks` and `register_routes` functions.

```
public function register_field() {
	$type = ( 'post_tag' === $this->type ) ? 'tag' : $this->type;
	register_rest_field( $type, 'acf', array(
		'get_callback' => array( $this, 'register_field_callback' ),
		'schema' => array(
			'description' => __( 'Expose advanced custom fields.', 'acf-to-rest-api' ),
			'type'        => 'object',
		),
	) );
}
```
