### ISSUE TITLE
Support for Revisions

### ISSUE THREAD

**Issue by Rayraz** [airesvsg/acf-to-rest-api#65]
Hey, thanks for the awesome plugin.

I was missing acf fields when retrieving post revisions. I managed to hack some support together with the filter below, but I'm not sure this is the safest option considering you probably wouldn't want to insert/update revisions directly as if they were a post type like any other.

```
function acf_revision_support($types)
{
    $types['revision'] = 'revision';

    return $types;
}
add_filter('acf/rest_api/types', 'acf_revision_support');
```

I can try and create a custom controller that rejects any attempt to insert or update, but I'm not sure how to properly integrate one with the plugin. Any pointers here would be helpful and of course I can provide a pull-request of the result if I find a working solution.

**Comment by airesvsg** [comment]
Hi @Rayraz,
sorry for the delay.

It's safe, because use the main controller: 
https://github.com/airesvsg/acf-to-rest-api/blob/master/class-acf-to-rest-api.php#L69

The best solution to integrate is put the type `revision` inside the array `$default`, see more detail here:
https://github.com/airesvsg/acf-to-rest-api/blob/master/class-acf-to-rest-api.php#L50

Thanks

**Comment by apandichi** [comment]
@airesvsg Any tips on how we can get support for revisions in v3 of this plugin? I see that the `'acf/rest_api/types'` filter is deprecated. The problem I'm having is that any updates I make to ACF fields through the REST API do not get recorded in the WP revisions list.
