### ISSUE TITLE
Request: how to exclude ACF from a call

### ISSUE THREAD

**Issue by davecarlson** [airesvsg/acf-to-rest-api#98]
When getting a post by either ID or slug, I would like the acf returned, as is the current functionality when doing a call such as 

```
/wp-json/wp/v2/posts?slug=the-post-in-question`
```

However, I do not want the acf fields coming down the wire when i'm getting a list of posts, like
```
/wp-json/wp/v2/posts`
```

As there is a lot of data that is never used in this instance. 

Is it possible to do something like an `exclude_field=acf` - I can't see it in the docs.

Thanks

**Comment by airesvsg** [comment]
Hello @davecarlson,
Thanks for you question, so you can use this code below.
```PHP
add_filter( 'acf/rest_api/post/get_fields', function( $data, $request, $response ) {
    $field = isset( $_GET['exclude_field'] ) ? esc_attr( $_GET['exclude_field'] ) : NULL;
    
    if ( $response instanceof WP_REST_Response ) {
        $data = $response->get_data();
        if ( $field && isset( $data[$field] ) ) {
        	unset( $data[$field] );
        }
    }

    return $data;
}, 10, 3 );
```

Thanks

**Comment by davecarlson** [comment]
<img width="409" alt="screen shot 2017-01-17 at 12 33 27 pm" src="https://cloud.githubusercontent.com/assets/299702/22020633/281895a4-dcb1-11e6-8dfa-e01d3229abb1.png">


Confirmed this solution works. Thanks a lot !

**Comment by charlesswanson** [comment]
I made two tweaks to the solution posted above:
1.) I added the code to a new plugin. I'm new to wordpress, but I think putting this logic in a plugin is better than the theme's functions.php file -- you might want to change themes without having to move this code.
2.) It seems the $response argument is no longer supplied. I modified the code:

```
add_filter( 'acf/rest_api/post/get_fields', function( $data, $request) {
  $field = isset( $_GET['exclude_field'] ) ? esc_attr( $_GET['exclude_field'] ) : NULL;

  // if ( $field && $response instanceof WP_REST_Response ) {
  if ( $field ) {
    if ( isset( $data[$field] ) ) {
      unset( $data[$field] );
    }
  }

  return $data;
}, 10, 2 );
```

My only remaining question is....does this just filter it out from being sent to the browser? That is, the backend php code is still calculating the ACFs for each post. Is there a way to disable ACF from running entirely on post listing requests? It might be important for performance if you're listing 100 posts... this question might be more for the ACF plugin rather than acf-to-reset-api, but I'm new to all this wordpress stuff.

**Comment by airesvsg** [comment]
Hi @charlesswanson,
You can use the filter `acf/rest_api/items_permissions/get` to remove the permission to list the acf data.
```PHP
add_filter( 'acf/rest_api/items_permissions/get', function( $permission, $request, $type ) {
   if ( 'my_custom_post' === $type ) {
      return false;
   }
}, 10, 3 );
```
Thanks
